# [torgfirmaBradley]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [torgfirmaBradley]    Script Date: 29.11.2021 20:48:14 ******/
CREATE DATABASE [torgfirmaBradley]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'torgfirmaBradley', FILENAME = N'G:\MSSQLServer Developer 2016\MSSQL13.STEPSQL\MSSQL\DATA\torgfirmaBradley.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'torgfirmaBradley_log', FILENAME = N'G:\MSSQLServer Developer 2016\MSSQL13.STEPSQL\MSSQL\DATA\torgfirmaBradley_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [torgfirmaBradley] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [torgfirmaBradley].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [torgfirmaBradley] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET ARITHABORT OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [torgfirmaBradley] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [torgfirmaBradley] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET  ENABLE_BROKER 
GO
ALTER DATABASE [torgfirmaBradley] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [torgfirmaBradley] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET RECOVERY FULL 
GO
ALTER DATABASE [torgfirmaBradley] SET  MULTI_USER 
GO
ALTER DATABASE [torgfirmaBradley] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [torgfirmaBradley] SET DB_CHAINING OFF 
GO
ALTER DATABASE [torgfirmaBradley] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [torgfirmaBradley] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [torgfirmaBradley] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'torgfirmaBradley', N'ON'
GO
ALTER DATABASE [torgfirmaBradley] SET QUERY_STORE = OFF
GO
USE [torgfirmaBradley]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

# [antipov]

In [0]:
USE [torgfirmaBradley]
GO

In [0]:
/****** Object:  User [antipov]    Script Date: 29.11.2021 20:48:14 ******/
CREATE USER [antipov] FOR LOGIN [antipov] WITH DEFAULT_SCHEMA=[dbo]
GO

In [0]:
ALTER ROLE [db_owner] ADD MEMBER [antipov]
GO

# [dbo].[klient]

In [0]:
/****** Object:  Table [dbo].[klient]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[klient](
	[id_klient] [int] IDENTITY(1,1) NOT NULL,
	[Nazva] [varchar](20) NULL,
	[Index_p] [char](5) NULL,
	[Addr] [varchar](50) NULL,
	[City] [varchar](20) NULL,
	[Region] [varchar](50) NULL,
	[tel] [char](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_klient] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[postachalnik]

In [0]:
/****** Object:  Table [dbo].[postachalnik]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[postachalnik](
	[id_postach] [int] IDENTITY(1,1) NOT NULL,
	[Nazva] [varchar](20) NULL,
	[Index_p] [char](5) NULL,
	[Addr] [varchar](50) NULL,
	[City] [varchar](20) NULL,
	[Region] [varchar](50) NULL,
	[tel] [char](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_postach] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Sotrudnik]

In [0]:
/****** Object:  Table [dbo].[Sotrudnik]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sotrudnik](
	[id_sotrudnik] [int] IDENTITY(1,1) NOT NULL,
	[Fname] [varchar](20) NULL,
	[Name] [varchar](20) NULL,
	[Posada] [varchar](40) NULL,
	[Date_enter] [date] NULL,
	[Date_birthday] [date] NULL,
	[Index_p] [char](5) NULL,
	[Adress] [varchar](50) NULL,
	[City] [varchar](20) NULL,
	[Region] [varchar](20) NULL,
	[Country] [varchar](20) NULL,
	[Tel] [char](12) NULL,
	[Foto] [varchar](50) NULL,
	[Note] [text] NULL,
 CONSTRAINT [PK__Sotrudni__0055D33CFA0B45B0] PRIMARY KEY CLUSTERED 
(
	[id_sotrudnik] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Tablesdrow]

In [0]:
/****** Object:  Table [dbo].[Tablesdrow]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tablesdrow](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[_name] [varchar](50) NULL,
	[_count] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[tovar]

In [0]:
/****** Object:  Table [dbo].[tovar]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[tovar](
	[id_tovar] [int] IDENTITY(1,1) NOT NULL,
	[Nazva_t] [varchar](20) NULL,
	[Min_zap] [int] NULL,
	[Zap_skl] [int] NULL,
	[price] [money] NULL,
	[post_prek] [smallint] NULL,
	[id_postach] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_tovar] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Zakaz]

In [0]:
/****** Object:  Table [dbo].[Zakaz]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Zakaz](
	[K_zakaz] [int] IDENTITY(1,1) NOT NULL,
	[K_klien] [int] NULL,
	[K_sotrud] [int] NULL,
	[Date_rozm] [date] NULL,
	[Date_naznach] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[K_zakaz] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[zakaz_tovar]

In [0]:
/****** Object:  Table [dbo].[zakaz_tovar]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[zakaz_tovar](
	[id_zakaz] [int] NOT NULL,
	[id_tovar] [int] NOT NULL,
	[kilk] [int] NULL,
	[znigka] [decimal](3, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_zakaz] ASC,
	[id_tovar] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [priceTovar]

In [0]:
/****** Object:  Index [priceTovar]    Script Date: 29.11.2021 20:48:14 ******/
CREATE NONCLUSTERED INDEX [priceTovar] ON [dbo].[tovar]
(
	[price] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER INDEX [priceTovar] ON [dbo].[tovar] DISABLE
GO

# [DF__klient__Index_p__5DCAEF64]

In [0]:
ALTER TABLE [dbo].[klient] ADD  DEFAULT ((10000)) FOR [Index_p]
GO

# [DF__torgfirma__Index__25869641]

In [0]:
ALTER TABLE [dbo].[postachalnik] ADD  DEFAULT ((10000)) FOR [Index_p]
GO

# [DF__Sotrudnik__Index__7C4F7684]

In [0]:
ALTER TABLE [dbo].[Sotrudnik] ADD  CONSTRAINT [DF__Sotrudnik__Index__7C4F7684]  DEFAULT ((10000)) FOR [Index_p]
GO

# [DF__tovar__Min_zap__2C3393D0]

In [0]:
ALTER TABLE [dbo].[tovar] ADD  DEFAULT ((10)) FOR [Min_zap]
GO

# [DF__Zakaz__Date_rozm__151B244E]

In [0]:
ALTER TABLE [dbo].[Zakaz] ADD  DEFAULT (getdate()) FOR [Date_rozm]
GO

# [DF__Zakaz__Date_nazn__160F4887]

In [0]:
ALTER TABLE [dbo].[Zakaz] ADD  DEFAULT (getdate()+(10)) FOR [Date_naznach]
GO

# [FK__tovar__id_postac__2E1BDC42]

In [0]:
ALTER TABLE [dbo].[tovar]  WITH CHECK ADD FOREIGN KEY([id_postach])
REFERENCES [dbo].[postachalnik] ([id_postach])
ON DELETE CASCADE
GO

# [FK__Zakaz__K_klien__1332DBDC]

In [0]:
ALTER TABLE [dbo].[Zakaz]  WITH CHECK ADD FOREIGN KEY([K_klien])
REFERENCES [dbo].[klient] ([id_klient])
GO

# [FK__Zakaz__K_sotrud__14270015]

In [0]:
ALTER TABLE [dbo].[Zakaz]  WITH CHECK ADD  CONSTRAINT [FK__Zakaz__K_sotrud__14270015] FOREIGN KEY([K_sotrud])
REFERENCES [dbo].[Sotrudnik] ([id_sotrudnik])
GO
ALTER TABLE [dbo].[Zakaz] CHECK CONSTRAINT [FK__Zakaz__K_sotrud__14270015]
GO

# [FK__zakaz_tov__id_to__1CBC4616]

In [0]:
ALTER TABLE [dbo].[zakaz_tovar]  WITH CHECK ADD  CONSTRAINT [FK__zakaz_tov__id_to__1CBC4616] FOREIGN KEY([id_tovar])
REFERENCES [dbo].[tovar] ([id_tovar])
GO
ALTER TABLE [dbo].[zakaz_tovar] CHECK CONSTRAINT [FK__zakaz_tov__id_to__1CBC4616]
GO

# [FK__zakaz_tov__id_za__1BC821DD]

In [0]:
ALTER TABLE [dbo].[zakaz_tovar]  WITH CHECK ADD  CONSTRAINT [FK__zakaz_tov__id_za__1BC821DD] FOREIGN KEY([id_zakaz])
REFERENCES [dbo].[Zakaz] ([K_zakaz])
GO
ALTER TABLE [dbo].[zakaz_tovar] CHECK CONSTRAINT [FK__zakaz_tov__id_za__1BC821DD]
GO

# [cityformat]

In [0]:
ALTER TABLE [dbo].[klient]  WITH CHECK ADD  CONSTRAINT [cityformat] CHECK  (([City] like 'м. [А-я]%'))
GO
ALTER TABLE [dbo].[klient] CHECK CONSTRAINT [cityformat]
GO

# [CK__klient__tel__5FB337D6]

In [0]:
ALTER TABLE [dbo].[klient]  WITH CHECK ADD CHECK  (([tel] like '([0-9][0-9][0-9])[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
GO

# [intformat]

In [0]:
ALTER TABLE [dbo].[klient]  WITH CHECK ADD  CONSTRAINT [intformat] CHECK  (([index_p] like '[0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[klient] CHECK CONSTRAINT [intformat]
GO

# [nazvaformat]

In [0]:
ALTER TABLE [dbo].[klient]  WITH CHECK ADD  CONSTRAINT [nazvaformat] CHECK  (([Nazva] like '[А-я]%'))
GO
ALTER TABLE [dbo].[klient] CHECK CONSTRAINT [nazvaformat]
GO

# [city_format]

In [0]:
ALTER TABLE [dbo].[postachalnik]  WITH CHECK ADD  CONSTRAINT [city_format] CHECK  (([City] like 'м. [А-я]%'))
GO
ALTER TABLE [dbo].[postachalnik] CHECK CONSTRAINT [city_format]
GO

# [CK__torgfirmaBr__tel__276EDEB3]

In [0]:
ALTER TABLE [dbo].[postachalnik]  WITH CHECK ADD CHECK  (([tel] like '([0-9][0-9][0-9])[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
GO

# [ind_format]

In [0]:
ALTER TABLE [dbo].[postachalnik]  WITH CHECK ADD  CONSTRAINT [ind_format] CHECK  (([index_p] like '[0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[postachalnik] CHECK CONSTRAINT [ind_format]
GO

# [nazva_format]

In [0]:
ALTER TABLE [dbo].[postachalnik]  WITH CHECK ADD  CONSTRAINT [nazva_format] CHECK  (([Nazva] like '[А-я]%'))
GO
ALTER TABLE [dbo].[postachalnik] CHECK CONSTRAINT [nazva_format]
GO

# [city__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [city__format] CHECK  (([city] like '[А-Я]%'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [city__format]
GO

# [CK__Sotrudnik__Tel__00200768]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [CK__Sotrudnik__Tel__00200768] CHECK  (([tel] like '([0-9][0-9][0-9])[0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [CK__Sotrudnik__Tel__00200768]
GO

# [country__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [country__format] CHECK  (([country] like '[А-Я]%'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [country__format]
GO

# [Fname__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [Fname__format] CHECK  (([Fname] like '[А-Я]%'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [Fname__format]
GO

# [ind__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [ind__format] CHECK  (([index_p] like '[0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [ind__format]
GO

# [name__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [name__format] CHECK  (([name] like '[А-Я]%'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [name__format]
GO

# [posada__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [posada__format] CHECK  (([posada] like '[А-Я]%'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [posada__format]
GO

# [region__format]

In [0]:
ALTER TABLE [dbo].[Sotrudnik]  WITH CHECK ADD  CONSTRAINT [region__format] CHECK  (([region] like '[А-Я]%'))
GO
ALTER TABLE [dbo].[Sotrudnik] CHECK CONSTRAINT [region__format]
GO

# [CK__tovar__Min_zap__2B3F6F97]

In [0]:
ALTER TABLE [dbo].[tovar]  WITH CHECK ADD CHECK  (([Min_zap]>(0)))
GO

# [CK__tovar__post_prek__2D27B809]

In [0]:
ALTER TABLE [dbo].[tovar]  WITH CHECK ADD CHECK  (([post_prek]=(1) OR [post_prek]=(0)))
GO

# [nazva_tf]

In [0]:
ALTER TABLE [dbo].[tovar]  WITH CHECK ADD  CONSTRAINT [nazva_tf] CHECK  (([Nazva_t] like '[А-я]%'))
GO
ALTER TABLE [dbo].[tovar] CHECK CONSTRAINT [nazva_tf]
GO

# [CK__zakaz_tova__kilk__1DB06A4F]

In [0]:
ALTER TABLE [dbo].[zakaz_tovar]  WITH CHECK ADD CHECK  (([kilk]>(0)))
GO

# [dbo].[abcdefg]

In [0]:
/****** Object:  StoredProcedure [dbo].[abcdefg]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[abcdefg]
AS
BEGIN
	declare @NAME varchar(50),@COUNT int,@QUARRY nvarchar(max)
	declare Alltab cursor for select TABLE_NAME from INFORMATION_SCHEMA.TABLES
	if (exists(select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'Tablesdrow'))
		drop table Tablesdrow
	
	create table Tablesdrow(
	id int PRIMARY KEY identity(1,1),
	_name varchar(50),
	_count int
	)
		
	open Alltab
	fetch next from Alltab into @NAME
	while @@FETCH_STATUS = 0
	begin
		
		print 'NAME '+@NAME
		set @QUARRY = N'SELECT @COUNT = COUNT(*) FROM ' + @NAME;
		print 'QUARRY '+@QUARRY
		EXEC sp_executesql @QUARRY, N'@COUNT int output', @COUNT = @COUNT output;
		print 'COUNT '+cast(@COUNT as varchar(15))
		insert into Tablesdrow (_name,_count) values (@NAME,@COUNT);
		fetch next from Alltab into @NAME

		
	end
	
	close Alltab
	deallocate Alltab

END
GO

# [dbo].[inserttobd]

In [0]:
/****** Object:  StoredProcedure [dbo].[inserttobd]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[inserttobd]
@klient int,
@id_tovar int,
@ammount int
as
begin
	declare @idzak int
	insert into [dbo].[Zakaz] ([K_klien],[K_sotrud],[Date_rozm]) values
	(@klient,3,GETDATE())
	set @idzak = @@identity
	insert into [dbo].[zakaz_tovar]([id_zakaz],[id_tovar],[kilk]) values
	(@idzak,@id_tovar,@ammount)
end;
GO

# [dbo].[postTovar]

In [0]:
/****** Object:  StoredProcedure [dbo].[postTovar]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[postTovar] 
AS
BEGIN
declare @idPost int,@NazvaP varchar(50),@nazvaT varchar(50),@zap int
declare post cursor for Select [Nazva],[id_postach] from [dbo].[postachalnik]
open post
fetch next from post into @NazvaP,@idPost
while (@@FETCH_STATUS = 0)
begin
print @NazvaP
	declare	tovar cursor for Select [Nazva_t],[Zap_skl] from [dbo].[tovar]
	where [id_postach] = @idPost
	open tovar
	fetch next from tovar into @nazvaT,@zap
	while(@@FETCH_STATUS = 0)
	begin
	print '  '+@nazvaT+' - '+cast(@zap as varchar(50))
	fetch next from tovar into @nazvaT,@zap
	end
	close tovar
	deallocate tovar
fetch next from post into @NazvaP,@idPost
end


END
close post
deallocate post
GO

# [dbo].[sotrudnik_otchet]

In [0]:
/****** Object:  StoredProcedure [dbo].[sotrudnik_otchet]    Script Date: 29.11.2021 20:48:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sotrudnik_otchet]
as
begin
	declare @Fname varchar(50),@id_sotrud int,@Nazva_klient varchar(50),@id_klient int,@Nazva_t varchar(50),@SumPrice int,@Zakazid int
	declare sotr cursor for Select [Fname],[id_sotrudnik] from dbo.Sotrudnik
	open sotr
	fetch next from sotr into @Fname,@id_sotrud
	while(@@FETCH_STATUS = 0)
	begin 
		print 'Сотрудник '+@Fname
		declare klient cursor for Select distinct id_klient ,Nazva from dbo.klient
		INNER JOIN dbo.Zakaz ON dbo.klient.id_klient = dbo.Zakaz.K_klien
		where K_sotrud = @id_sotrud 
		open klient
			fetch next from klient into @id_klient,@Nazva_klient
		while(@@FETCH_STATUS = 0)
		begin
			print '    Клиент ' + @Nazva_klient
			
			declare tovar cursor for Select [K_zakaz],[Nazva_t], SUM(kilk*price) from dbo.tovar
			LEFT JOIN dbo.zakaz_tovar ON dbo.tovar.id_tovar = dbo.zakaz_tovar.id_tovar 
			LEFT JOIN dbo.Zakaz ON dbo.zakaz_tovar.id_zakaz = dbo.Zakaz.K_zakaz
			where K_sotrud = @id_sotrud and K_klien = @id_klient
			group by K_zakaz,Nazva_t
			open tovar
			fetch next from tovar into @Zakazid,@Nazva_t,@SumPrice
			while(@@FETCH_STATUS = 0)
			begin
				print '        Nomer: '+Cast(@Zakazid as varchar(50))+', '+@Nazva_t+', Sum (' +Cast(@SumPrice as varchar(50))+')'
				fetch next from tovar into @Zakazid,@Nazva_t,@SumPrice
			end
			close tovar
			deallocate tovar
			fetch next from klient into @id_klient,@Nazva_klient
		end
	
		fetch next from sotr into @Fname,@id_sotrud
		close klient
		deallocate klient
	select @SumPrice = SUM(kilk * price) from dbo.Sotrudnik 
		INNER JOIN dbo.Zakaz ON dbo.Sotrudnik.id_sotrudnik = dbo.Zakaz.K_sotrud 
		INNER JOIN dbo.zakaz_tovar ON dbo.Zakaz.K_zakaz = dbo.zakaz_tovar.id_zakaz 
		INNER JOIN dbo.tovar ON dbo.zakaz_tovar.id_tovar = dbo.tovar.id_tovar
		where id_sotrudnik=@id_sotrud
		group by id_sotrudnik
		print ' Total Sum : '++cast(@SumPrice as varchar(50))

	end

	close sotr
	deallocate sotr
end;


exec sotrudnik_otchet
GO

# [torgfirmaBradley]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [torgfirmaBradley] SET  READ_WRITE 
GO